name: API Assistant CI/CD

on:
  push:
    branches:
      - main

jobs:
  deploy:
    name: Deploy
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Node.js
        uses: actions/setup-node@v2
        with:
          node-version: 18

      - name: Pull cached dependencies
        id: cache-dependencies
        uses: actions/cache@v2
        env:
          cache-name: cache-dependencies
        with:
          path: node_modules
          key: ${{ runner.os }}-build-${{ env.cache-name }}-${{ hashFiles('**/package-lock.json') }}
          
      - name: Install dependencies if cache hit does not happen
        if: steps.cache-dependencies.outputs.cache-hit != 'true'
        run: npm install

      - name: Build affected apps/libs
        run: npm run build:affected

      - name: Test affected apps/libs
        run: npm run test:affected
        
      - name: Deploy
        uses: appleboy/ssh-action@master
        with:
            host: ${{ secrets.SSH_HOST }}
            username: ${{ secrets.SSH_USERNAME }}
            key: ${{ secrets.SSH_PASS }}
            script: |
              cd applications/api-assistant
              git pull origin main

              npm install

              npx nx build backend
              cp ./.env ./dist/apps/backend
              pm2 restart 0

              npx nx build frontend
              sudo nginx -s reload
